### ISSUE TITLE
Fix format error on debug logging

### ISSUE THREAD

**Issue by rsp9u** [side-runner-py/side-runner-py#40]
SSIA

**Comment by rsp9u** [comment]
Examples; 
```
runner_1_95f3a7316fc0 | DEBUG:side_runner_py.commands:TYPE:
runner_1_95f3a7316fc0 | --- Logging error ---
runner_1_95f3a7316fc0 | Traceback (most recent call last):
runner_1_95f3a7316fc0 |   File "/usr/local/lib/python3.7/logging/__init__.py", line 1034, in emit
runner_1_95f3a7316fc0 |     msg = self.format(record)
runner_1_95f3a7316fc0 |   File "/usr/local/lib/python3.7/logging/__init__.py", line 880, in format
runner_1_95f3a7316fc0 |     return fmt.format(record)
runner_1_95f3a7316fc0 |   File "/usr/local/lib/python3.7/logging/__init__.py", line 619, in format
runner_1_95f3a7316fc0 |     record.message = record.getMessage()
runner_1_95f3a7316fc0 |   File "/usr/local/lib/python3.7/logging/__init__.py", line 380, in getMessage
runner_1_95f3a7316fc0 |     msg = msg % self.args
runner_1_95f3a7316fc0 | TypeError: not all arguments converted during string formatting
```
