### ISSUE TITLE
Issue while running test

### ISSUE THREAD

**Issue by qb-nimish** [side-runner-py/side-runner-py#68]
2020-07-01T10:15:30Z WARNING side_runner_py.main: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/side_runner_py-0.0.8-py3.7.egg/side_runner_py/main.py", line 53, in execute_test_command
    handler_func(session_manager.driver, session_manager.variable_store, test_project, test_suite, test_dict)
  File "/usr/local/lib/python3.7/site-packages/side_runner_py-0.0.8-py3.7.egg/side_runner_py/commands.py", line 63, in execute_click
    element = _wait_element(driver, test_dict['target'])
  File "/usr/local/lib/python3.7/site-packages/side_runner_py-0.0.8-py3.7.egg/side_runner_py/commands.py", line 57, in _wait_element
    element = WebDriverWait(driver, Config.DRIVER_ELEMENT_WAIT).until(condition)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by rsp9u** [comment]
@qb-nimish The DOM element is not found with the locator that you specified.
The element may not exist or may be hidden.
Please review the locator in 'target' and your test target web site.
