### ISSUE TITLE
Error in test; Failed to execute 'elementsFromPoint' on 'Document'

### ISSUE THREAD

**Issue by qb-nimish** [side-runner-py/side-runner-py#69]
2020-07-02T11:28:21Z WARNING side_runner_py.main: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/side_runner_py-0.0.8-py3.7.egg/side_runner_py/main.py", line 54, in execute_test_command
    handler_func(session_manager.driver, session_manager.variable_store, test_project, test_suite, test_dict)
  File "/usr/local/lib/python3.7/site-packages/side_runner_py-0.0.8-py3.7.egg/side_runner_py/commands.py", line 68, in execute_click
    ActionChains(driver).click(element).perform()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Failed to execute 'elementsFromPoint' on 'Document': The provided double value is non-finite.
  (Session info: chrome=83.0.4103.116)

**Comment by rsp9u** [comment]
@qb-nimish It may have occurred due to the manipulation for the element inside `frame`.
I'm going to impl `selectFrame` command, so try it when it's implemented.
